### ISSUE TITLE
Clickable link parser broken

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#185]
Originally reported by: **Anonymous**

----------------------------------------

If a posted link has surrounding <> chars, the parser fails to remove the > at the end.

Example: 

User: Check out my homepage <http://domain/whatever.html>

Clickable link points to http://domain/whatever.html>

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/201

**Comment by retropc** [comment]
trying to figure out what the user meant from the url is basically impossible, sorry
