### ISSUE TITLE
User bypasses G-Line

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#227]
Originally reported by: **Anonymous**

----------------------------------------

So when the user connects with an actual client(irssi or mIRC) and they are G-Lined then they get banned, when they try to connect using Mibbit they are still banned. When they try to use qwebirc they get passed the gline, any ideas what could be wrong?

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/264

**Comment by retropc** [comment]
notabug
