### ISSUE TITLE
[PATCH] BNC Auth (ident/password) support

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#234]
Originally reported by: **[DodgeX](https://bitbucket.org/DodgeX) (Bitbucket)**

----------------------------------------

As i wanted a nice webchat for my bouncer, i decided to use qwebirc but as it only supports use nick as ident, and not use nick x and ident y i added this feature. that the bouncer does not nick-changes to the ident and the user is force to nickchange to its normal nick again.

i added an new option for the IDENT setting in config.py that lets qwebirc use the ident provided on login. also i've added an ident inputfield that has to be enabled via js/auth.js qwebirc.auth.bouncerIdent (new) returning true

patch is attached. feel free to commit it, or refuse it.

maybe you need/want to modify some of my changes to better fit the system... it is currently a cleaned version of my "get this to work"-rush but as its meant to be free for everyone, feel free to modify.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/290

**Comment by retropc** [comment]
patch is gone :/
