### ISSUE TITLE
MOTD's are not in their proper window

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#239]
Originally reported by: **Anonymous**

----------------------------------------

When I login to multiple chatroom at the same time, the MOTD/ChanServe messages are all sent to the current tab/chatroom that is open.

If I were to log in, then join the rooms using the /join #room the messages would appear in the proper windows.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/298

**Comment by retropc** [comment]
don't see how
