### ISSUE TITLE
removal of slap feature

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#241]
Originally reported by: **Anonymous**

----------------------------------------

Hey I'm a member of a forum which uses one of your IRC clients. I was wondering why you guys created the slap feature. Personally I don't find it necessary given that its only purpose is to create or aid drama within the client whereas drama occurs in the client a lot without the use of that feature. I also find it troublesome because it's right next to the query feature. I've miscklicked the slap button when I intended to click the query button on a mod in the client. Although the mod forgave me in time I still find it very unnecessary and troublesome.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/301

**Comment by retropc** [comment]
no!
