### ISSUE TITLE
When kicked, You can't see the reason.

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#244]
Originally reported by: **[Aha2Y](https://bitbucket.org/Aha2Y) (Bitbucket)**

----------------------------------------

When you get kicked, You can't see the reason with qwebirc.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/306

**Comment by retropc** [comment]
pretty certain you can

**Comment by retropc** [comment]
just tested it, you see it in status window
