### ISSUE TITLE
Nickname stuck forever in IRC when browser crashed or closed abnorbally

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#249]
Originally reported by: **[lion_mrr](https://bitbucket.org/lion_mrr) (Bitbucket)**

----------------------------------------

Only restarting qwebirc or /nickserv ghost (if nick registered) can wipe out this stuck users.
I tried last qwebirc version and this issue still remains. So I write patch that works for me http://lion.rusfur.net/ircclient.py
Simply adds timeout to QWebIRCClient class. Note that I use not last version of qwebirc, too lazy for update.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/312

**Comment by retropc** [comment]
ping timeout is supposed to resolve this on the ircd side
