### ISSUE TITLE
Error simplejson in Windows 8 64 Bit

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#281]
Originally reported by: **[xose_bmnz](https://bitbucket.org/xose_bmnz) (Bitbucket)**

----------------------------------------

C:\xampp\htdocs\irc>compile.py
first run, checking dependencies...
warning: simplejson module with C speedups not installed.
warning: using embedded module (slower); consider installing simplejson from:
warning: http://pypi.python.org/pypi/simplejson/

0 errors, 1 warnings.
you can run qwebirc despite these.

C:\xampp\htdocs\irc>

setup.py install simplejson 2.6.2 and 3.3.1 | python25

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/360

**Comment by retropc** [comment]
not a bug
