### ISSUE TITLE
Add webchat to your site fails to include location.port

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#285]
Originally reported by: **[adrian1](https://bitbucket.org/adrian1) (Bitbucket)**

----------------------------------------

I try to create a link for
http://webchat.mozilla-tunisia.org:9090/

The resulting link, however, is
http://webchat.mozilla-tunisia.org/?nick=name&channels=devtools&uio=d4
while it needs to be
http://webchat.mozilla-tunisia.org/?nick=name&channels=devtools&uio=d4
for it to actually work.

Please include location.port in the construction of the link.

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/385

**Comment by retropc** [comment]
config issue
