### ISSUE TITLE
CentOS 7 Twisted Names Module Error When Running compile.py

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#288]
Originally reported by: **[geeklex](https://bitbucket.org/geeklex) (Bitbucket)**

----------------------------------------

I get the following error when trying to compile on CentOS 7

( see attached )

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/388

**Comment by retropc** [comment]
attachement seems to have gone
