### ISSUE TITLE
Turkish language problem

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#293]
Originally reported by: **[jiyan](https://bitbucket.org/jiyan) (Bitbucket)**

----------------------------------------

I get the Turkish language problems during chat   
I made arrangements ircclient.py but other users will see different characters

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/393

**Comment by retropc** [comment]
only utf8 supported
