### ISSUE TITLE
Website repo doesn't allow issues to be logged (and broken links on website)

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#296]
Originally reported by: **[ryancross](https://bitbucket.org/ryancross) (Bitbucket)**

----------------------------------------

Not sure if this is meant to force people to log issues against the website to this repo, but I couldn't seem to log an issue againt https://bitbucket.org/qwebirc/qwebirc.org

I wanted to point out that the website has a broken link to the issue queue. Both the "bugs" and "wishlist/todo" links point to deadlinks. 

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/397

**Comment by retropc** [comment]
fixed
