### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#298]
Originally reported by: **[uniwebs](https://bitbucket.org/uniwebs) (Bitbucket)**

----------------------------------------

Hi !
Anyone can tell me how i can install qwebirc in my shared hosting Account?
http://irc.aajfm.com/
Thanks

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/400

**Comment by retropc** [comment]
notabug
