### ISSUE TITLE
Problem in query with nickname change

### ISSUE THREAD

**Issue by fishbot2000** [qwebirc/qwebirc#302]
Originally reported by: **[Scrown](https://bitbucket.org/Scrown) (Bitbucket)**

----------------------------------------

Hello,

I have a bug into qwebirc, I have test it on your version before writing this issue and it also present.

When I send a message to user "test" it's ok :
<Scrown> test
<test> message received

If "test" change his nickname, I can message him but I don't receive the answer :
*test2* test *<< It should be "<scrown> test" here*
<test2> message received

if "test2" change again, he can't receive my message :
*test2* test
--- test3 doesn't receive my message ---

I think the problem is the window is not attributed to the new nickname when user change.

I hope you can help me. 

Scrown

----------------------------------------
- Bitbucket: https://bitbucket.org/qwebirc/qwebirc/issue/404

**Comment by retropc** [comment]
fixed

**Comment by jmmizah** [comment]
problem wrongly solved


watch the video

https://www.youtube.com/watch?v=LdnUJF2WVUI
