### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by Indjov** [qwebirc/qwebirc#313]
Hello, 
We use an IRCD that supports UTF nicknames and Cyrillic channels, but  but unfortunately your webchat has problems with Cyrillic nicks and channels, he put all Cyrillic channel and nicknames in one tab.
If i try to join in 2/3/4 cyrillic channels i will join but everything shows in only on channel tab and that it`s the firs channel where we can join. The same it`s happend with the nicknames.

Any idea how to fix that

**Comment by retropc** [comment]
what's your server?

**Comment by Indjov** [comment]
@retropc ,what you mean about server? IRC or Web?

bgchat.eu:7744
