### ISSUE TITLE
QuakeNet autostoring user information 

### ISSUE THREAD

**Issue by lirre0xF** [qwebirc/qwebirc#320]
Hello QuakeNet,
I'd like to see a cookie and "preference settings" being enforced. 
Autocomplete information on nickname and channel when you connect via webchat via Log In to Q.

My suggestion is that:
Once a user press Log In to Q, then if they've set "channel" and "nickname", it'll be stored.

Example:
User register on QuakeNet -> Press Log In to Q -> it'll remember which was the user's favorite channel and favorite nickname. In that way, users don't have to put in their nickname or which channels they want to join.

**Comment by retropc** [comment]
fixed
