### ISSUE TITLE
Im so inbarrased

### ISSUE THREAD

**Issue by MADLIBSX** [qwebirc/qwebirc#334]
All I want to do is learn how all this works I am an intelligent person that learns by trial and error and hands on the best.  I dont know if I am making mistakes that violate any rules.  i was in persuite to comunicate with people that share the same fealings on views.  I feal bad now if i have been shut out because I made an unconsious mistake

**Comment by MADLIBSX** [comment]
[](url)
[Uploading ChangeLog
[ChangeLog.txt](https://github.com/qwebirc/qwebirc/files/1372496/ChangeLog.txt)
.txt…]()

**Comment by retropc** [comment]
ok
