### ISSUE TITLE
qwebirc + ssl certs + lets encrypt needs reload cert feature 

### ISSUE THREAD

**Issue by nixbits** [qwebirc/qwebirc#338]
When using qwebirc with certificates there is no reload feature to update qweirc and make it use the new certificate.
In the old days when people typically only renewed certificates once a year this was not much of a trouble as one would only need to restart qwebirc.

However, nowadays when using certificates from lets encrypt, becomes a bit troublesome to restart every 2 or 3 months and disconnect connected users at the time.

This is where a new feature that would allow qwebirc to reload the certificates would come handy and solve this problem. A reload.py script for such task is necessary.

Related info:
`ARGS = "-p 6697 -C cert.pem -k key.pem -H fullchain.pem"`

**Comment by retropc** [comment]
it's only really for testing, I should document this really

in "production" a proper load balancer/reverse proxy should be used

**Comment by YuGiOhJCJ** [comment]
Is there a way to reload the certificates now? I have the same problem.
On the Mumble server for example, we send a SIGUSR1 signal to the process for reloading certificates: https://wiki.mumble.info/wiki/Obtaining_a_Let%27s_Encrypt_Murmur_Certificate
Something similar for qwebirc could be a good feature.
