### ISSUE TITLE
Update SSL support to allow only secure ciphers

### ISSUE THREAD

**Issue by nezgit** [qwebirc/qwebirc#353]
Hello,

<Warning: I am a n00b, but use qweb very actively, and love it>.

SSL support was enabled some time ago. Doing a check of the SSL security (i.e. ssllabs.com), I notice qweb (i think?) is allowing legacy ciphers, and for instance SSL 3. Is there a way to update the SSL support to enforce now standard SSL security protocols and ciphers; or is there another fix for this, i.e. configure OpenSSL on the machine qweb is running on?

I note there are easy fixes for instance with Apache, where one can remove support for instance for SSL3, in the .conf file.

Understand that SSL is probably not utilized by most of the qweb users, but for me it is quite important.

Thanks

**Comment by kshrc** [comment]
what qwebirc version ? paste you config.py  u need settings ssl on machine running qwebirc and u ircd.conf too 
# OPTION: SSLPORT
#         SSL port of IRC server to connect to.
#         If this option is uncommented it will override IRCPORT.
SSLPORT = 6697

# OPTION: REALNAME 
u machine have ssl configured qwebirc connect without problems to u ircd

**Comment by kshrc** [comment]
what qwebirc version ? paste you config.py u need settings ssl on machine running qwebirc and u ircd.conf too

OPTION: SSLPORT
SSL port of IRC server to connect to.
If this option is uncommented it will override IRCPORT.
SSLPORT = 6697

OPTION: REALNAME
u machine have ssl configured qwebirc connect without problems to u ircd
