### ISSUE TITLE
Installation Guide: No instruction to download the code

### ISSUE THREAD

**Issue by begleysm** [qwebirc/qwebirc#361]
In the Installation Guide at https://qwebirc.org/installation the user is never, explicitly, told to download (clone) the sour code.

I recommend adding a bullet between "First install the dependencies for your operating system: " and "Copy config.py.example to config.py, and edit it to fit your network's setup." that says something like: 

"Visit the [downloads](https://qwebirc.org/download) page, acquire the source code, and navigate into the source code's root directory."

**Comment by retropc** [comment]
feel free to send a pull request with the changes
