### ISSUE TITLE
Feature: Send on connect

### ISSUE THREAD

**Issue by Marabon** [qwebirc/qwebirc#362]
It'd be great if there'd be an easy way to make the client send a string/command defined by us on connect.
I need the client to send an invite string to a bot which then invites them into appropriate channels.

I've tried to modify the code to make it send it but haven't gotten it to work.
By passing a passphrase in the URL when embedding the chat I'd like to use that passphrase in the invite string sent on connect.

**Comment by retropc** [comment]
this is deliberately not supported by default

if it's your instance and you want help making the changes pop into our irc channel
