### ISSUE TITLE
Client/user doesn't leave channel until ping timeout when page is refreshed from embedded client

### ISSUE THREAD

**Issue by n-ham** [qwebirc/qwebirc#364]
If I open up the normal freenode web irc client, enter a channel then refresh the page, the client/user exits the channel and a 'Client quit' message appears for those still in the channel. 

However if I use an embedded client for a site, enter a channel then refresh the page, the client/user doesn't leave the room until there's a ping time out. It would be convenient to know when a user is no longer in the chat room even if that's caused from them refreshing the page. 

This behaviour is happening for me using Chromium Version 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit), in case it does not occur everywhere else.

**Comment by retropc** [comment]
this is by design
