### ISSUE TITLE
Just installed qwebirc on Centos 7, started it but it won't join any channel

### ISSUE THREAD

**Issue by MiguelX88** [qwebirc/qwebirc#388]
Hi, i have just installed, configured and running qwebIRC on CentOS 7 but when It connects to my server I can see the username joining my Auto-connect channels but any channel on qwebIRC is opened.  Nickname is connected, it's on the irc servers, it's on channels but on qwebIRC no channel is open why? Who can help me to solve please?

I installed those packages for start qwebirc:

attrs==19.3.0
autobahn==19.11.2
Automat==20.2.0
constantly==15.1.0
hyperlink==19.0.0
simplejson==3.17.0
incremental==17.5.0
six==1.15.0
Twisted==20.3.0
txaio==18.8.1
zope.interface==4.7.2

Thanks so much for reply.

**Comment by yudumnet** [comment]
Run these commands respectively 👍 
pip install -r requirements.txt
./clean.py
./compile.py
./run.py
